FROM node:alpine

WORKDIR /usr/src/app

COPY . .

# Install application dependencies and cleanup in one RUN command
RUN set -eux; \
    npm install; \
    npm install nodemon -g \
    npm cache clean --force

# RUN npm run build

CMD [ "npm" ,"run", "dev" ]